### ISSUE TITLE
Cannot build error at cmake 

### ISSUE THREAD

**Issue by ulisesac4** [rocm-arch/python-torchaudio-rocm#5]
This is the trace I am getting:

```
Traceback (most recent call last):
  File "/home/ulisesac/.cache/yay/python-torchaudio-rocm/src/audio/setup.py", line 184, in <module>
    _main()
  File "/home/ulisesac/.cache/yay/python-torchaudio-rocm/src/audio/setup.py", line 147, in _main
    setup(
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ulisesac/.cache/yay/python-torchaudio-rocm/src/audio/tools/setup_helpers/extension.py", line 86, in run
    super().run()
  File "/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ulisesac/.cache/yay/python-torchaudio-rocm/src/audio/tools/setup_helpers/extension.py", line 168, in build_extension
    subprocess.check_call(["cmake", "--build", "."] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-torchaudio-rocm-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
python-torchaudio-rocm - exit status 4

```

I recently re installed arch on this PC, so I am not sure if there is a missing dependency on my system because before doing the reinstall I could install this package.

**Comment by JulianWogersien** [comment]
same but theres actually a relevant part of the log missing:
```
-- Could NOT find HIP: Found unsuitable version "0.0.0", but required is at least "1.0" (found /opt/rocm)
HIP VERSION: 0.0.0
CMake Warning at /usr/lib/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/lib/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:85 (include)


-- Found Torch: /usr/lib/libtorch.so
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Could not find ccache. Consider installing ccache to speed up compilation.
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
Updated 0 paths from the index
-- Configuring done (2.1s)
CMake Error at /usr/lib/cmake/Caffe2/Caffe2Targets.cmake:107 (set_target_properties):
  The link interface of target "torch_hip_library" contains:

    roc::hipblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/lib/cmake/Caffe2/Caffe2Config.cmake:113 (include)
  /usr/lib/cmake/Torch/TorchConfig.cmake:68 (find_package)
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:85 (include)

```
This is directly over the traceback
